name: brain
channels:
  - conda-forge
  - defaults
dependencies:
  # Core direct requirements
  - python=3.11.7
  - transformers=4.37.2
  - numpy=1.26.3
  - pandas=2.1.4
  - scipy=1.12.0
  - scikit-learn=1.4.1
  
  # Data handling and compression
  - zstandard=0.22.0 
  - pyarrow=14.0.2   
  
  # Audio processing
  - librosa=0.10.1
  
  # Development environment (direct)
  - jupyterlab=4.2.2
  - ipywidgets=8.1.3
  - matplotlib=3.8.0
  
  # Utils (direct)
  - tqdm=4.66.4
  
  # Pip packages (direct)
  - pip
  - pip:
    - datasets==2.17.0
    - tokenizers==0.15.2
    - mne==1.6.1  # Only if you're doing EEG/MEG analysis
    - mne-bids==0.14  # Only if you're doing EEG/MEG analysis

